# Generated by Django 4.1.7 on 2023-02-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=300, verbose_name='Language (eg. English, Russian)')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and time when the language is added')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300, verbose_name='Word')),
                ('description', models.TextField(verbose_name="Word's description")),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and time when the word is added')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.language')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=300, verbose_name="Word's translation")),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and time when the translation is added')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=300, verbose_name="Word's hint")),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and time when the hint is added')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
    ]
