# Generated by Django 4.1.7 on 2023-02-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_translation_language_alter_word_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='language',
            new_name='translation_language',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='language',
            new_name='word_language',
        ),
    ]
